/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rugbyapp;

/**
 *
 * @author blras
 */
public class AddProductGUI extends javax.swing.JFrame {

    /**
     * Creates new form AddProductGUI
     */
    public AddProductGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddBtn = new javax.swing.JToggleButton();
        ViewBtn = new javax.swing.JToggleButton();
        AddProductLbl = new javax.swing.JLabel();
        ProductTypeLabel = new javax.swing.JLabel();
        TypeComboBox = new javax.swing.JComboBox<>();
        ProductNameLabel = new javax.swing.JLabel();
        ProductNameTf = new javax.swing.JTextField();
        QuantityLabel = new javax.swing.JLabel();
        QuantityTf = new javax.swing.JTextField();
        PriceLabel = new javax.swing.JLabel();
        PriceTf = new javax.swing.JTextField();
        TeamLabel = new javax.swing.JLabel();
        SleeveTypeLabel = new javax.swing.JLabel();
        CollarTypeLabel = new javax.swing.JLabel();
        GloveTypeLabel = new javax.swing.JLabel();
        TeamTf = new javax.swing.JTextField();
        SleeveComboBox = new javax.swing.JComboBox<>();
        CollarComboBox = new javax.swing.JComboBox<>();
        GloveTypeComboBox = new javax.swing.JComboBox<>();
        GloveMaterialLabel = new javax.swing.JLabel();
        GloveMaterialComboBox = new javax.swing.JComboBox<>();
        WeatherTypeLabel = new javax.swing.JLabel();
        WeatherComboBox = new javax.swing.JComboBox<>();
        StudTypeLabel = new javax.swing.JLabel();
        StudComboBox = new javax.swing.JComboBox<>();
        AddProductBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddBtn.setText("Add Product");

        ViewBtn.setText("View Product");

        AddProductLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AddProductLbl.setText("Add Product");

        ProductTypeLabel.setText("Product Type");

        TypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jersey", "Boots", "Gloves", " " }));

        ProductNameLabel.setText("Product Name");

        ProductNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductNameTfActionPerformed(evt);
            }
        });

        QuantityLabel.setText("Quantity");

        PriceLabel.setText("Price");

        TeamLabel.setText("Team");

        SleeveTypeLabel.setText("SleeveType");

        CollarTypeLabel.setText("Collar Type");

        GloveTypeLabel.setText("Glove Type");

        SleeveComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Long Sleeve", "Short Sleeve", "No Sleeve", " " }));

        CollarComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Round Collar", "V-Neck Collar", "Default Collar" }));

        GloveTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fingerless Gloves", "Full Gloves" }));

        GloveMaterialLabel.setText("Glove Material");

        GloveMaterialComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cotton", "Leather", "Linen" }));
        GloveMaterialComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GloveMaterialComboBoxActionPerformed(evt);
            }
        });

        WeatherTypeLabel.setText("Weather Type");

        WeatherComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dry Weather", "Wet Weather" }));

        StudTypeLabel.setText("Stud Type");

        StudComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metal Studs", "Plastic Studs" }));

        AddProductBtn.setText("Add Product");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ProductTypeLabel)
                                    .addComponent(ProductNameLabel)
                                    .addComponent(QuantityLabel)
                                    .addComponent(PriceLabel)
                                    .addComponent(TeamLabel)
                                    .addComponent(CollarTypeLabel)
                                    .addComponent(GloveTypeLabel)
                                    .addComponent(SleeveTypeLabel)
                                    .addComponent(GloveMaterialLabel)
                                    .addComponent(WeatherTypeLabel)
                                    .addComponent(StudTypeLabel))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ProductNameTf)
                                    .addComponent(QuantityTf)
                                    .addComponent(PriceTf)
                                    .addComponent(GloveTypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TeamTf)
                                    .addComponent(SleeveComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CollarComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GloveMaterialComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(WeatherComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(StudComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ViewBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddProductLbl)
                            .addComponent(AddProductBtn))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBtn)
                    .addComponent(ViewBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddProductLbl)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductTypeLabel)
                    .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductNameLabel)
                    .addComponent(ProductNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityLabel)
                    .addComponent(QuantityTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceLabel)
                    .addComponent(PriceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeamTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeamLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SleeveTypeLabel)
                    .addComponent(SleeveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CollarTypeLabel)
                    .addComponent(CollarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GloveTypeLabel)
                    .addComponent(GloveTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GloveMaterialLabel)
                    .addComponent(GloveMaterialComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WeatherTypeLabel)
                    .addComponent(WeatherComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudTypeLabel)
                    .addComponent(StudComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(AddProductBtn)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductNameTfActionPerformed

    private void GloveMaterialComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GloveMaterialComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GloveMaterialComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProductGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProductGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProductGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProductGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProductGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AddBtn;
    private javax.swing.JToggleButton AddProductBtn;
    private javax.swing.JLabel AddProductLbl;
    private javax.swing.JComboBox<String> CollarComboBox;
    private javax.swing.JLabel CollarTypeLabel;
    private javax.swing.JComboBox<String> GloveMaterialComboBox;
    private javax.swing.JLabel GloveMaterialLabel;
    private javax.swing.JComboBox<String> GloveTypeComboBox;
    private javax.swing.JLabel GloveTypeLabel;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JTextField PriceTf;
    private javax.swing.JLabel ProductNameLabel;
    private javax.swing.JTextField ProductNameTf;
    private javax.swing.JLabel ProductTypeLabel;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JTextField QuantityTf;
    private javax.swing.JComboBox<String> SleeveComboBox;
    private javax.swing.JLabel SleeveTypeLabel;
    private javax.swing.JComboBox<String> StudComboBox;
    private javax.swing.JLabel StudTypeLabel;
    private javax.swing.JLabel TeamLabel;
    private javax.swing.JTextField TeamTf;
    private javax.swing.JComboBox<String> TypeComboBox;
    private javax.swing.JToggleButton ViewBtn;
    private javax.swing.JComboBox<String> WeatherComboBox;
    private javax.swing.JLabel WeatherTypeLabel;
    // End of variables declaration//GEN-END:variables
}
